### ISSUE TITLE
poetry run azulejo ingest tests/testdata/glyma+glyso.toml fails

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/azulejo#198]
Output directory: glycines/
Extracting FASTA/GFF info for 2 genomes:
[                                        ] | 0% Completed |  1.2s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click_loguru/__init__.py", line 238, in wrapper
    return user_func(*args, **kwargs)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/click_loguru/__init__.py", line 250, in wrapper
    returnobj = user_func(*args, **kwargs)
  File "/erdos/adf/code/azulejo/azulejo/__init__.py", line 741, in ingest
    undeco_ingest_sequences(input_toml, click_loguru=click_loguru)
  File "/erdos/adf/code/azulejo/azulejo/ingest.py", line 166, in ingest_sequences
    file_stats = bag.map(
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/multiprocessing.py", line 218, in get
    result = get_async(
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/multiprocessing.py", line 119, in reraise
    raise exc
dask.multiprocessing.FileNotFoundError: [Errno 2] No such file or directory: 'glyma.Wm82.gnm4.ann1.T8TQ.protein_primaryTranscript.faa'

Traceback
---------
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/bag/core.py", line 1777, in reify
    seq = list(seq)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/dask/bag/core.py", line 1964, in __next__
    return self.f(*vals)
  File "/erdos/adf/code/azulejo/azulejo/ingest.py", line 232, in read_fasta_and_gff
    with read_from_url(fasta_url) as fasta_fh:
  File "/erdos/adf/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/erdos/adf/code/azulejo/azulejo/ingest.py", line 612, in read_from_url
    yield smart_open.open(url)
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 181, in open
    fobj = _shortcut_open(
  File "/home/localhost/adf/.cache/pypoetry/virtualenvs/azulejo-MJzWr3oj-py3.8/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 364, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)

**Comment by adf-ncgr** [comment]
not a bug, I expected this toml file to have remote references, but apparently it does not.
